/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/l51dBZLQGGE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "~/components/ui/card"
import { Link } from "@remix-run/react";

export function Bio() {
  return (
    <div className="max-w-2xl mx-auto p-4">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold">JB Tellez</h1>
        <p className="text-muted-foreground">Full Stack Developer</p>
      </div>
      <div className="space-y-4">
        <p>
        Hi there! I’m an experienced educational software engineer and instructor based in Seattle, WA. My journey in the tech industry spans over two decades, during which I’ve developed a diverse skill set in multiple programming languages and frameworks. I have a proven track record in engineering educational software and mentoring team mates in advanced programming.</p>
        <p>Check out example applications built with varying stacks:</p>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Snacks with Remix</CardTitle>
            </CardHeader>
            <CardContent>
              <p>A full stack web application built with Remix, FastAPI, and Supabase.</p>
            </CardContent>
            <CardFooter>
              <Link to="https://remix-snacks.vercel.app/" className="text-primary">
                View Project
              </Link>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Snacks with FastAPI</CardTitle>
            </CardHeader>
            <CardContent>
              <p>Interactive JSON API built with FastAPI and Supabase.</p>
            </CardContent>
            <CardFooter>
              <Link to="https://fastsnacks1-ykq3ctu6.b4a.run/docs" className="text-primary" prefetch={false}>
                View Project
              </Link>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}
