/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ijUKET0moWc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function Glance() {
  return (
    <section className="w-full max-w-3xl mx-auto py-12 md:py-16 lg:py-20" id="at-a-glance">
      <div className="space-y-6">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">Me at a Glance</h1>
          
        </div>
        <div className="space-y-4">
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">8+ years building fullstack interactive web applications</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Demonstrate a strong understanding of JavaScript, HTML, and CSS, and the ability to use them to build
                responsive and interactive web applications.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Capable of designing simple yet resilient system and application architectures</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Proficiency in at least one JavaScript framework or library, such as React, Angular, or Vue.js, and the
                ability to use it to build complex web applications.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Highly collaborative working style and able to communicate ideas and decisions well</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Familiarity with server-side technologies, such as Node.js, Express, or PHP, and the ability to build
                and integrate APIs.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">You’ve led at least one product-focused engineering team</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Knowledge of database technologies, such as SQL or NoSQL databases, and the ability to design and
                implement database schemas.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Proficient in Typescript, React and Node</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Familiarity with web development best practices, such as responsive design, accessibility, and security.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
            <div className="flex h-6 w-6 items-center justify-center rounded-full bg-yellow-500">
                <CircleDashedIcon className="h-4 w-4 text-white" />
              </div>
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Competent in cloud deployment and cloud management practices (e.g. kubernetes)</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Demonstrated ability to collaborate with other developers, designers, and stakeholders to deliver
                high-quality web applications.
              </p>
            </div>
          </div>
          
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Care about the monitoring, alerting and processes that reduce risk so the team can sleep easily at night</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Commitment to staying up-to-date with the latest web development technologies and best practices, and a
                willingness to learn and improve continuously.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Interested in and want to learn about the latest AI technologies</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Commitment to staying up-to-date with the latest web development technologies and best practices, and a
                willingness to learn and improve continuously.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Bonus: worked on creative or educational platforms in the past</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Commitment to staying up-to-date with the latest web development technologies and best practices, and a
                willingness to learn and improve continuously.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <div className="flex-shrink-0">
              <CheckIcon className="h-6 w-6 text-green-500" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold">Bonus: experience with Remix or Python</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Commitment to staying up-to-date with the latest web development technologies and best practices, and a
                willingness to learn and improve continuously.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}


function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}

function CircleDashedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10.1 2.182a10 10 0 0 1 3.8 0" />
      <path d="M13.9 21.818a10 10 0 0 1-3.8 0" />
      <path d="M17.609 3.721a10 10 0 0 1 2.69 2.7" />
      <path d="M2.182 13.9a10 10 0 0 1 0-3.8" />
      <path d="M20.279 17.609a10 10 0 0 1-2.7 2.69" />
      <path d="M21.818 10.1a10 10 0 0 1 0 3.8" />
      <path d="M3.721 6.391a10 10 0 0 1 2.7-2.69" />
      <path d="M6.391 20.279a10 10 0 0 1-2.69-2.7" />
    </svg>
  )
}
