/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hgstbXXlxyP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Link } from "@remix-run/react";
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Textarea } from "~/components/ui/textarea"
import { Button } from "~/components/ui/button"
import Glance from "~/components/glance"

export default function Pitch() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" to="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Resume</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#at-a-glance">
            At a Glance
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#experience">
            Experience
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#skills">
            Skills
          </Link>
          
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48" id="hero">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  JB Tellez
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Full-Stack Engineer
                </p>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Hi there. I really like the work you're doing. 
                </p>
              </div>
              <div className="animate-bounce">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-4 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  to="#at-a-glance"
                >
                  <ChevronDownIcon className="h-5 w-5" />
                </Link>
              </div>
            </div>
          </div>
        </section>
        <Glance />
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800" id="about">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">About</div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">8+ Years of Full-Stack Experience</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    As a principal full-stack engineer, I have extensive experience in designing and developing
                    scalable, resilient web applications. I'm highly collaborative and focused on delivering
                    high-quality, user-centric solutions.
                  </p>
                </div>
              </div>
              <img
                alt="About"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="experience">
          <div className="container px-4 md:px-6">
            <div className="space-y-6">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Experience</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Proven Track Record</h2>
              </div>
              <div className="grid gap-6 lg:grid-cols-2">
                <div className="flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <BriefcaseIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    <div className="space-y-1">
                      <div className="text-lg font-semibold">Principal Instructor</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <a className="underline" href="https://www.codefellows.org/">Code Fellows</a> | 2017 - 2024
                      </div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                  Trained adult learners with little to no coding experience to advanced levels in JavaScript and Python. Co-created curriculum that plays to individual strengths for rapid yet solid progress. Managed instructor team with focus on supporting underrepresented groups in tech.
                  </p>
                </div>
                <div className="flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <BriefcaseIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    <div className="space-y-1">
                      <div className="text-lg font-semibold">Director of Engineering</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <a className="underline" href="https://rippleeffects.com/">Ripple Effects</a> | 2012 - 2017
                      </div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                  Developed desktop, mobile, and web applications for preK-12 learners using various languages and frameworks. Collaborated with educators to enhance application effectiveness. Researched and implemented best development tools and practices, reducing risk and improving efficiency. Contributed to strategic decision-making with leadership.
                  </p>
                </div>
                <div className="flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <BriefcaseIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    <div className="space-y-1">
                      <div className="text-lg font-semibold">Sr. Software Engineer</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <a className="underline" href="https://smashingideas.com/">Smashing Ideas</a> | 2010 - 2012
                      </div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                  Spearheaded online game development from concept to launch, leading teams on large-scale game suites. Optimized tools and workflows for web and mobile development. Collaborated with clients to design engaging game mechanics and balance gameplay for maximum user experience.</p>
                </div>
                <div className="flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <BriefcaseIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    <div className="space-y-1">
                      <div className="text-lg font-semibold">Sr. Software Engineer</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        <a className="underline" href="https://scilearn.com/">Scientific Learning</a> | 1999 - 2009
                      </div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                  Created educational games to enhance literacy for k-12 learners. Led front-end development team, implemented middleware for seamless communication between display and Java backend. Conducted code reviews, developed educational apps, and designed data upload and persistence strategies. Researched and evaluated cutting-edge development tools and processes, including XP, TDD, UML, and Design Patterns, to optimize team efficiency and product quality.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800" id="skills">
          <div className="container px-4 md:px-6">
            <div className="space-y-6">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Skills</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Expertise and Capabilities</h2>
              </div>
              <div className="grid grid-cols-2 gap-6 sm:grid-cols-3 lg:grid-cols-4">
                <div className="flex flex-col items-center gap-2">
                  <CodeIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">Full-Stack Development</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CpuIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">System Architecture</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <UsersIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">Collaboration</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <RocketIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">Product Leadership</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CodeIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">TypeScript</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <ComponentIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">React</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <NetworkIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">Node.js</div>
                </div>
                <div className="flex flex-col items-center gap-2">
                  <CloudIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                  <div className="text-sm font-medium">Cloud Deployment</div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t" id="contact">
          <div className="container px-4 md:px-6">
            <div className="space-y-6">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Contact</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Get in Touch</h2>
              </div>
              <div className="mx-auto w-full max-w-md space-y-4">
                <form className="grid gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="John Doe" required />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="john@example.com" required type="email" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="message">Message</Label>
                    <Textarea id="message" placeholder="How can I help you?" required rows={5} />
                  </div>
                  <Button className="w-full" type="submit">
                    Submit
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 John Doe. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function ComponentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>
  )
}


function CpuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
